#!/usr/bin/env python3
"""Collect selected output figures into a report-ready asset package."""

from __future__ import annotations

import argparse
import csv
import shutil
from collections import defaultdict
from pathlib import Path


OVERLAY_PATTERNS = [
    "*_components_color.png",
    "*_mask_comparison.png",
    "*_infection_overlay.png",
]


def read_csv(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        raise FileNotFoundError(f"CSV not found: {path}")
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        return list(csv.DictReader(handle))


def safe_name(value: str) -> str:
    cleaned = []
    for char in value.strip() or "item":
        cleaned.append(char if char.isalnum() or char in "-_." else "_")
    return "".join(cleaned)


def copy_file(source: Path, destination: Path) -> bool:
    if not source.exists() or not source.is_file():
        return False
    destination.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source, destination)
    return True


def collect_svg_figures(source_dir: Path, output_dir: Path, manifest_lines: list[str]) -> int:
    copied = 0
    if not source_dir.exists():
        manifest_lines.append(f"- SVG figures: skipped, directory not found: `{source_dir}`")
        return copied

    for source in sorted(source_dir.glob("*.svg")):
        destination = output_dir / "summary" / source.name
        if copy_file(source, destination):
            manifest_lines.append(f"- Copied summary figure: `{destination}`")
            copied += 1
    return copied


def collect_case_overlays(
    dataset_summary: Path,
    output_dir: Path,
    max_cases_per_dataset: int,
    max_images_per_case: int,
    manifest_lines: list[str],
) -> int:
    rows = read_csv(dataset_summary)
    copied = 0
    seen_by_dataset: dict[str, int] = defaultdict(int)

    for row in rows:
        if row.get("status") != "ok":
            continue
        dataset = row.get("dataset_kind", "unknown")
        if seen_by_dataset[dataset] >= max_cases_per_dataset:
            continue

        case_id = row.get("case_id", "case")
        output_root = Path(row.get("output_root", ""))
        overlay_dir = output_root / "overlays"
        if not overlay_dir.exists():
            continue

        case_copied = 0
        destination_dir = output_dir / "cases" / safe_name(dataset) / safe_name(case_id)
        for pattern in OVERLAY_PATTERNS:
            for source in sorted(overlay_dir.glob(pattern)):
                if case_copied >= max_images_per_case:
                    break
                destination = destination_dir / source.name
                if copy_file(source, destination):
                    copied += 1
                    case_copied += 1
                    manifest_lines.append(f"- Copied case figure: `{destination}`")
            if case_copied >= max_images_per_case:
                break

        if case_copied > 0:
            seen_by_dataset[dataset] += 1

    return copied


def write_manifest(output_dir: Path, manifest_lines: list[str]) -> Path:
    manifest = output_dir / "ASSET_MANIFEST.md"
    manifest.parent.mkdir(parents=True, exist_ok=True)
    content = ["# Report Asset Package", "", "Generated assets:", "", *manifest_lines, ""]
    manifest.write_text("\n".join(content), encoding="utf-8")
    return manifest


def collect_assets(
    dataset_summary: Path,
    figures_dir: Path,
    output_dir: Path,
    max_cases_per_dataset: int,
    max_images_per_case: int,
) -> tuple[int, Path]:
    manifest_lines: list[str] = []
    copied = 0
    copied += collect_svg_figures(figures_dir, output_dir, manifest_lines)
    copied += collect_case_overlays(
        dataset_summary,
        output_dir,
        max_cases_per_dataset,
        max_images_per_case,
        manifest_lines,
    )

    if copied == 0:
        manifest_lines.append("- No assets copied. Run dataset batch processing and figure generation first.")
    manifest = write_manifest(output_dir, manifest_lines)
    return copied, manifest


def main() -> int:
    parser = argparse.ArgumentParser(description="Collect selected result images/SVGs for report and PPT use.")
    parser.add_argument(
        "--dataset-summary",
        default="results/datasets/dataset_summary.csv",
        type=Path,
        help="Path to dataset_summary.csv generated by dataset batch processing.",
    )
    parser.add_argument(
        "--figures-dir",
        default="results/figures",
        type=Path,
        help="Directory containing SVG figures generated by generate_report_figures.py.",
    )
    parser.add_argument(
        "--output-dir",
        default="report/figures",
        type=Path,
        help="Destination directory for the report asset package.",
    )
    parser.add_argument("--max-cases-per-dataset", default=2, type=int)
    parser.add_argument("--max-images-per-case", default=6, type=int)
    args = parser.parse_args()

    copied, manifest = collect_assets(
        args.dataset_summary,
        args.figures_dir,
        args.output_dir,
        max(1, args.max_cases_per_dataset),
        max(1, args.max_images_per_case),
    )
    print(f"Copied {copied} asset(s).")
    print(f"Manifest: {manifest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
